# 20 INBUILT PANDAS WITH EXAMPLES

In [6]:
import pandas as pd


In [2]:
filename ='Online Retail Dataset.csv'
filepath = 'C:\Kaggle Set'

In [3]:
fullFileDir = filepath + '/' + filename



In [4]:
fullFileDir

'C:\\Kaggle Set/Online Retail Dataset.csv'

In [8]:
fullFileDir = filepath + '/'+filename
df = pd.read_csv(fullFileDir)

In [9]:
df

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
542009    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
542010    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
542011    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
542012    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
542013    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

             InvoiceDate  UnitPrice  CustomerID         Country  
0        01/12/2010 8:26       2.55     17850.0  United Kingdom  
1        01/12/2010 8:26       3.39     17850.0  United Kingdom  
2        01/12/2010 8:26       2.75     17850.0  United Kingdom  
3        01/12/2010 8:26       3.39     17850.0  United Kingdom  
4        01/12/2010 8:26       3.39     17850.0  United Kingdom  
...                  ...        ...         ...             ...  
542009  09/12/2011 12:50       0.85     12680.0          France  
542010  09/12/2011 12:50       2.10     12680.0          France  
542011  09/12/2011 12:50       4.15     12680.0          France  
542012  09/12/2011 12:50       4.15     12680.0          France  
542013  09/12/2011 12:50       4.95     12680.0          France  

[542014 rows x 8 columns]

In [11]:
df.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

       InvoiceDate  UnitPrice  CustomerID         Country  
0  01/12/2010 8:26       2.55     17850.0  United Kingdom  
1  01/12/2010 8:26       3.39     17850.0  United Kingdom  
2  01/12/2010 8:26       2.75     17850.0  United Kingdom  
3  01/12/2010 8:26       3.39     17850.0  United Kingdom  
4  01/12/2010 8:26       3.39     17850.0  United Kingdom

In [12]:
df.tail()

InvoiceNo StockCode                      Description  Quantity  \
542009    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12   
542010    581587     22899     CHILDREN'S APRON DOLLY GIRL          6   
542011    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4   
542012    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4   
542013    581587     22138    BAKING SET 9 PIECE RETROSPOT          3   

             InvoiceDate  UnitPrice  CustomerID Country  
542009  09/12/2011 12:50       0.85     12680.0  France  
542010  09/12/2011 12:50       2.10     12680.0  France  
542011  09/12/2011 12:50       4.15     12680.0  France  
542012  09/12/2011 12:50       4.15     12680.0  France  
542013  09/12/2011 12:50       4.95     12680.0  France

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542014 entries, 0 to 542013
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    542014 non-null  object 
 1   StockCode    542014 non-null  object 
 2   Description  540560 non-null  object 
 3   Quantity     542014 non-null  int64  
 4   InvoiceDate  542014 non-null  object 
 5   UnitPrice    542014 non-null  float64
 6   CustomerID   406934 non-null  float64
 7   Country      542014 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB


In [14]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [15]:
df.shape

(542014, 8)

In [16]:
df.size

4336112

In [17]:
df.describe

<bound method NDFrame.describe of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
542009    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
542010    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
542011    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
542012    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
542013    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

             InvoiceDate  UnitPrice  Cust

In [18]:
df.sample(5)

InvoiceNo StockCode                       Description  Quantity  \
71237     542109     84991       60 TEATIME FAIRY CAKE CASES         3   
122072    546837     22697   GREEN REGENCY TEACUP AND SAUCER         6   
179913    552287     22383            LUNCH BAG SUKI DESIGN         10   
249791    558906    84660A         WHITE STITCHED WALL CLOCK         2   
456710    575701     23213  STAR WREATH DECORATION WITH BELL        24   

             InvoiceDate  UnitPrice  CustomerID         Country  
71237   25/01/2011 13:44       1.25         NaN  United Kingdom  
122072  17/03/2011 12:37       2.95     13650.0  United Kingdom  
179913  08/05/2011 13:19       1.65     17705.0  United Kingdom  
249791  04/07/2011 16:35       0.79     15555.0  United Kingdom  
456710  10/11/2011 16:59       1.25     13396.0  United Kingdom

In [19]:
df.isnull

<bound method DataFrame.isnull of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
542009    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
542010    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
542011    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
542012    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
542013    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

             InvoiceDate  UnitPrice  Cust

In [20]:
df.isna().any()

InvoiceNo      False
StockCode      False
Description     True
Quantity       False
InvoiceDate    False
UnitPrice      False
CustomerID      True
Country        False
dtype: bool

In [23]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [24]:
df.nunique

<bound method DataFrame.nunique of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
542009    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
542010    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
542011    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
542012    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
542013    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

             InvoiceDate  UnitPrice  Cus

In [25]:
df.index

RangeIndex(start=0, stop=542014, step=1)

In [26]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [27]:
df.memory_usage()

Index              128
InvoiceNo      4336112
StockCode      4336112
Description    4336112
Quantity       4336112
InvoiceDate    4336112
UnitPrice      4336112
CustomerID     4336112
Country        4336112
dtype: int64

In [52]:
df.nsmallest(5, 'UnitPrice')

InvoiceNo StockCode      Description  Quantity       InvoiceDate  \
300088   A563186         B  Adjust bad debt         1  12/08/2011 14:51   
300089   A563187         B  Adjust bad debt         1  12/08/2011 14:52   
680       536414     22139              NaN        56  01/12/2010 11:52   
2075      536545     21134              NaN         1  01/12/2010 14:32   
2076      536546     22145              NaN         1  01/12/2010 14:33   

        UnitPrice  CustomerID         Country  
300088  -11062.06         NaN  United Kingdom  
300089  -11062.06         NaN  United Kingdom  
680          0.00         NaN  United Kingdom  
2075         0.00         NaN  United Kingdom  
2076         0.00         NaN  United Kingdom

In [51]:
df.nlargest(5, 'Quantity', )

InvoiceNo StockCode                        Description  Quantity  \
540526    581483     23843        PAPER CRAFT , LITTLE BIRDIE     80995   
61724     541431     23166     MEDIUM CERAMIC TOP STORAGE JAR     74215   
502227    578841     84826     ASSTD DESIGN 3D PAPER STICKERS     12540   
74719     542504     37413                                NaN      5568   
421737    573008     84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS      4800   

             InvoiceDate  UnitPrice  CustomerID         Country  
540526   09/12/2011 9:15       2.08     16446.0  United Kingdom  
61724   18/01/2011 10:01       1.04     12346.0  United Kingdom  
502227  25/11/2011 15:57       0.00     13256.0  United Kingdom  
74719   28/01/2011 12:03       0.00         NaN  United Kingdom  
421737  27/10/2011 12:26       0.21     12901.0  United Kingdom

In [48]:
df.loc[:5, ['Quantity', 'UnitPrice']]

Quantity  UnitPrice
0         6       2.55
1         6       3.39
2         8       2.75
3         6       3.39
4         6       3.39
5         2       7.65

In [53]:
df.iloc[:4,:8]

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   

       InvoiceDate  UnitPrice  CustomerID         Country  
0  01/12/2010 8:26       2.55     17850.0  United Kingdom  
1  01/12/2010 8:26       3.39     17850.0  United Kingdom  
2  01/12/2010 8:26       2.75     17850.0  United Kingdom  
3  01/12/2010 8:26       3.39     17850.0  United Kingdom

In [55]:
df[0:5]

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

       InvoiceDate  UnitPrice  CustomerID         Country  
0  01/12/2010 8:26       2.55     17850.0  United Kingdom  
1  01/12/2010 8:26       3.39     17850.0  United Kingdom  
2  01/12/2010 8:26       2.75     17850.0  United Kingdom  
3  01/12/2010 8:26       3.39     17850.0  United Kingdom  
4  01/12/2010 8:26       3.39     17850.0  United Kingdom

In [61]:
df.sort_index(axis=1, ascending = True)

Country  CustomerID                          Description  \
0       United Kingdom     17850.0   WHITE HANGING HEART T-LIGHT HOLDER   
1       United Kingdom     17850.0                  WHITE METAL LANTERN   
2       United Kingdom     17850.0       CREAM CUPID HEARTS COAT HANGER   
3       United Kingdom     17850.0  KNITTED UNION FLAG HOT WATER BOTTLE   
4       United Kingdom     17850.0       RED WOOLLY HOTTIE WHITE HEART.   
...                ...         ...                                  ...   
542009          France     12680.0          PACK OF 20 SPACEBOY NAPKINS   
542010          France     12680.0         CHILDREN'S APRON DOLLY GIRL    
542011          France     12680.0        CHILDRENS CUTLERY DOLLY GIRL    
542012          France     12680.0      CHILDRENS CUTLERY CIRCUS PARADE   
542013          France     12680.0        BAKING SET 9 PIECE RETROSPOT    

             InvoiceDate InvoiceNo  Quantity StockCode  UnitPrice  
0        01/12/2010 8:26    536365         6    85123A       2.55  
1        01/12/2010 8:26    536365         6     71053       3.39  
2        01/12/2010 8:26    536365         8    84406B       2.75  
3        01/12/2010 8:26    536365         6    84029G       3.39  
4        01/12/2010 8:26    536365         6    84029E       3.39  
...                  ...       ...       ...       ...        ...  
542009  09/12/2011 12:50    581587        12     22613       0.85  
542010  09/12/2011 12:50    581587         6     22899       2.10  
542011  09/12/2011 12:50    581587         4     23254       4.15  
542012  09/12/2011 12:50    581587         4     23255       4.15  
542013  09/12/2011 12:50    581587         3     22138       4.95  

[542014 rows x 8 columns]

In [63]:
df.sort_values(by='Country')

InvoiceNo StockCode                     Description  Quantity  \
304995    563614     23326   HANGING MINI COLOURED BOTTLES       192   
276439    561040     22138   BAKING SET 9 PIECE RETROSPOT          6   
276440    561040     22617      BAKING SET SPACEBOY DESIGN         6   
276441    561040     22729     ALARM CLOCK BAKELIKE ORANGE         4   
276442    561040     22698  PINK REGENCY TEACUP AND SAUCER         6   
...          ...       ...                             ...       ...   
282962    561661     22556  PLASTERS IN TIN CIRCUS PARADE          1   
282961    561661     22604  SET OF 4 NAPKIN CHARMS CUTLERY         2   
282960    561661     23188  VINTAGE  2 METER FOLDING RULER         1   
282969    561661     21065          BOOM BOX SPEAKER GIRLS         1   
308905    564051     22112      CHOCOLATE HOT WATER BOTTLE         3   

             InvoiceDate  UnitPrice  CustomerID      Country  
304995   18/08/2011 8:51       0.55     12415.0    Australia  
276439  24/07/2011 12:05       4.95     12431.0    Australia  
276440  24/07/2011 12:05       4.95     12431.0    Australia  
276441  24/07/2011 12:05       3.75     12431.0    Australia  
276442  24/07/2011 12:05       2.95     12431.0    Australia  
...                  ...        ...         ...          ...  
282962  28/07/2011 16:21       1.65     12743.0  Unspecified  
282961  28/07/2011 16:21       2.55     12743.0  Unspecified  
282960  28/07/2011 16:21       1.65     12743.0  Unspecified  
282969  28/07/2011 16:21       5.95     12743.0  Unspecified  
308905  22/08/2011 13:32       4.95     14265.0  Unspecified  

[542014 rows x 8 columns]

In [69]:
df.query('12000 < CustomerID < 17000')[:8]

InvoiceNo StockCode                         Description      InvoiceDate  \
9     536367     84879       ASSORTED COLOUR BIRD ORNAMENT  01/12/2010 8:34   
10    536367     22745          POPPY'S PLAYHOUSE BEDROOM   01/12/2010 8:34   
11    536367     22748           POPPY'S PLAYHOUSE KITCHEN  01/12/2010 8:34   
12    536367     22749           POPPY'S PLAYHOUSE KITCHEN  01/12/2010 8:34   
13    536367     22310             IVORY KNITTED MUG COSY   01/12/2010 8:34   
14    536367     84969  BOX OF 6 ASSORTED COLOUR TEASPOONS  01/12/2010 8:34   
15    536367     22623       BOX OF VINTAGE JIGSAW BLOCKS   01/12/2010 8:34   
16    536367     22622      BOX OF VINTAGE ALPHABET BLOCKS  01/12/2010 8:34   

    UnitPrice  CustomerID  
9        1.69     13047.0  
10       2.10     13047.0  
11       2.10     13047.0  
12       2.10     13047.0  
13       1.65     13047.0  
14       4.25     13047.0  
15       4.95     13047.0  
16       9.95     13047.0

#      ###20 IN BUILT NUMPY WITH EXAMPLES


In [75]:
import numpy as np


In [77]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [78]:
arr = np.array([1, 2, 3, 4])
print(arr[2]+ arr[3])

7


In [82]:

>>> a =np.arange(15).reshape(3,5)
>>> a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
>>> a.shape

(3, 5)

In [84]:
>>> a.ndim

2

In [85]:
>>> a.dtype.name

'int32'

In [86]:
>>> a.size

15

In [87]:
>>> type(a)

numpy.ndarray

In [89]:
>>> b =np.array([6,7,8])
>>> b

array([6, 7, 8])

In [91]:
>>> b = np.array([(1.5, 2, 3), (4, 5, 6)])
>>> b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [92]:
>>> np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
>>> np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [94]:
>>> np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [97]:
>>> print (np.arange(10000))
>>>
>>> print (np.arange(10000).reshape(100, 100))


[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [103]:
>>> a= np.arange(10)**3
>>> a
>>> a[2]
>>> a[2:5]

array([ 8, 27, 64], dtype=int32)

In [105]:
>>> def f(x,y):
    return 10 * x + y

>>> b =np.fromfunction(f,(5, 4), dtype =int)
>>> b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [106]:
>>> b [-1]

array([40, 41, 42, 43])

In [107]:
>>> for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [115]:
>>> a.ravel ()
>>> a.reshape(5, 2)

array([[  0,   1],
       [  8,  27],
       [ 64, 125],
       [216, 343],
       [512, 729]], dtype=int32)

In [118]:
>>> c =a. view()
>>> c is a


False

In [119]:
>>> c.base is a

True

In [120]:
>>> c.flags.owndata

False

In [124]:
>>> s = a[ 1:3]
>>> s[:] = 10
>>> a

array([  0,  10,  10,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [130]:
>>> d = a.copy()
>>> d is a



False

In [133]:
>>> a = np.arange(5)
>>> a[[0, 0, 2]] +=1
>>> a

array([1, 1, 3, 3, 4])